"""empty message

Revision ID: 69accc56d9c6
Revises: ecd8a9ee27e5
Create Date: 2020-05-03 16:01:39.789673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69accc56d9c6'
down_revision = 'ecd8a9ee27e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
